### ISSUE TITLE
Minor Documentation Update: JOSS review

### ISSUE THREAD

**Issue by sara-02** [lmiconsulting/cosasi#1]
One minor comment I have in the documentation is that the first quickstart examples present in readthedocs's main page https://cosasi.readthedocs.io/en/latest/index.html as well as the README here on GitHub has an image coded; it would be better to have the code in ```python``` format so that it can be copy pasted.
https://github.com/openjournals/joss-reviews/issues/4894

**Comment by lucasmccabe** [comment]
Hi @sara-02 - great point. I have updated both the [README](https://github.com/lmiconsulting/cosasi#code-snippet) and the [narrative documentation](https://cosasi.readthedocs.io/en/latest/) to reflect your recommendation. I kept the [Carbon](https://github.com/carbon-app/carbon) image because I think it's aesthetically pleasing, but I added an equivalent code snippet in `python` format for easier copying.

**Comment by lucasmccabe** [comment]
Hi @sara-02 - are we comfortable closing this issue, or would you prefer an alternative corrective?

**Comment by sara-02** [comment]
> Hi @sara-02 - are we comfortable with my closing this issue, or would you prefer an alternative corrective?

Yes
